CREATE TABLE IF NOT EXISTS Singers (
	id SERIAL PRIMARY KEY,
	name VARCHAR(80) NOT NULL
	);

CREATE TABLE IF NOT EXISTS Albums (
	album_id SERIAL PRIMARY KEY,
	name VARCHAR(80) NOT NULL,
	year INTEGER NOT NULL
	);

CREATE TABLE IF NOT EXISTS Collections (
	id SERIAL PRIMARY KEY,
	name VARCHAR(80) NOT NULL,
	year INTEGER NOT NULL
	);

CREATE TABLE IF NOT EXISTS Genre (
	id SERIAL PRIMARY KEY,
	name VARCHAR(80) NOT NULL
	);

CREATE TABLE IF NOT EXISTS Tracks (
	id SERIAL PRIMARY KEY,
	name VARCHAR(80) NOT NULL,
	time DECIMAL(8, 2) NOT NULL,
	album_id INTEGER NOT NULL REFERENCES Albums(album_id),
	FOREIGN KEY (album_id)  REFERENCES Albums (album_id)
	);

CREATE TABLE IF NOT EXISTS Singers_genres (
	id SERIAL PRIMARY KEY,
	singer_ID INTEGER NOT NULL REFERENCES Singers(id),
	genre_ID INTEGER NOT NULL REFERENCES Genre(id)
	);
	
CREATE TABLE IF NOT EXISTS Singers_albums (
	id SERIAL PRIMARY KEY,
	singer_ID INTEGER NOT NULL REFERENCES Singers(id),
	album_ID INTEGER NOT NULL REFERENCES Albums(album_id)
	);
	
CREATE TABLE IF NOT EXISTS Tracks_collection (
	id SERIAL PRIMARY KEY,
	track_ID INTEGER NOT NULL REFERENCES Tracks(id),
	collection_ID INTEGER NOT NULL REFERENCES Collections(id)
	);